### PR TITLE
Open app drawer with 'Home' button + design improvements

### PR DESCRIPTION
**Pull request by edpratti**

### CODE REVIEW

**Comment by ACHOKAMAN** [comment]
Why didn't they merge this please??did the development of this launcher stop???🤔🤔

**Comment by edpratti** [comment]
Development was stated to be very slow to non-existing from the start, since this was an experiment to show off the beautiful animations.

I wouldn't want to build unofficial versions regardless. I think that's a bit out of my jurisdiction.

**Comment by ACHOKAMAN** [comment]
No problem i just taught this could be something better in the future since it was even released to the playstore but i guess not so i will just reduced my enthusiasm.thanks for the reply

**Comment by ACHOKAMAN** [comment]
Thanks for merging this hope the apk will be uploaded soon to playstore...and hopefully more things will come in the future.....@prattiDev 😊😊

**Pull request merged**
